"""Phase 5 — Build a nested parse tree from LR(0) steps."""

# The parse_tree logic now works dynamically with any grammar generated by lr0.py


def build_tree(parse_steps: list[dict], tokens: list[dict] = None) -> dict | None:
    """
    Replay the parse steps to reconstruct a tree.
    Returns a nested {value, children} dict or None.
    """
    if not parse_steps:
        return None

    node_stack: list[dict] = []
    
    # We will track which token we are shifting
    token_idx = 0
    actual_tokens = [t for t in (tokens or []) if t["type"] not in ("ERROR",)]

    for step in parse_steps:
        action = step.get("action", "")

        if action.startswith("shift"):
            symbol = step["input"].split()[0] if step["input"].strip() else "?"
            actual_val = symbol
            if token_idx < len(actual_tokens):
                actual_val = actual_tokens[token_idx]["value"]
                token_idx += 1
            node_stack.append({"value": actual_val, "children": []})

        elif action.startswith("reduce"):
            # e.g. "reduce E → E + T"
            try:
                rhs_str = action.split("→")[-1].strip()
                rhs = rhs_str.split()
            except Exception:
                continue

            lhs_str = action.split("→")[0].replace("reduce", "").strip()
            children: list[dict] = []
            for _ in rhs:
                if node_stack:
                    children.insert(0, node_stack.pop())
            node_stack.append({"value": lhs_str, "children": children})

        elif action == "accept":
            break

    return node_stack[-1] if node_stack else {"value": "Program", "children": []}
