import { MCPExplanationResponse, Diagnostic } from '../types';
import { validateDiagnostic } from '../lingo/validator';
import glossary from '../lingo/glossary.json';

// ============================================================================
// MCP (Model Context Provider) EXPLANATION SERVICE
// Generates AI explanations for transformations with validation gate
// ============================================================================

const MAX_RETRIES = 3;

/**
 * Predefined explanations for transformation types
 * In production, these would be generated by LLM
 */
const TRANSFORMATION_EXPLANATIONS: Record<string, (params: Record<string, unknown>) => string> = {
  numberEncoding: (params) => `
    Number encoding transformation applied. The original constant value ${params.original ?? 'N'} 
    was encoded using arithmetic obfuscation with offset ${params.offset ?? 'K'}. 
    The encoding preserves semantic equivalence: the encoded expression evaluates to the 
    same value at runtime. This technique makes static analysis more difficult by hiding 
    literal constants.
  `.trim().replace(/\s+/g, ' '),

  substitution: (params) => `
    Instruction substitution applied to ${params.source ?? 'operation'}. 
    The arithmetic operation was replaced with a bitwise equivalent sequence: 
    a + b = (a XOR b) + 2 * (a AND b). This transformation preserves the computational 
    result while obscuring the original operation type. The bitwise sequence produces 
    identical output for all integer inputs.
  `.trim().replace(/\s+/g, ' '),

  opaquePredicates: (params) => `
    Opaque predicate injected using variable '${params.variable ?? 'x'}'. 
    The predicate (x*x + x) % 2 == 0 is mathematically always true for integers, 
    since x(x+1) is always even (one of x or x+1 must be even). This adds a conditional 
    branch that always takes the true path, but static analyzers cannot easily determine 
    this without symbolic reasoning.
  `.trim().replace(/\s+/g, ' '),

  flattening: (params) => `
    Control flow flattening applied to ${params.instruction ?? 'N'} instructions. 
    Linear code was transformed into a dispatcher loop with switch-case structure. 
    Each original instruction becomes a case in the switch, with state variable controlling 
    execution order. This obscures the program's control flow graph while preserving 
    execution semantics.
  `.trim().replace(/\s+/g, ' '),

  customRule: (params) => `
    Custom transformation rule applied. Source operation '${params.source ?? 'OP'}' 
    was expanded to target sequence '${params.target ?? 'SEQUENCE'}'. 
    This user-defined rule enables experimental obfuscation patterns. 
    The rule was applied ${params.hits ?? 0} time(s) during this compilation pass.
  `.trim().replace(/\s+/g, ' '),

  semanticPreservation: (params) => `
    Semantic preservation verified. The original IR produced output ${params.original ?? 'X'} 
    and the transformed IR produced output ${params.result ?? 'X'}. 
    ${params.preserved ? 'Values match - transformation is semantically correct.' : 
    'MISMATCH DETECTED - transformation may have introduced a bug.'}
  `.trim().replace(/\s+/g, ' '),
};

/**
 * Generate an explanation for a transformation type
 * Validates output against Lingo before returning
 */
export async function generateExplanation(
  transformationType: string,
  params: Record<string, unknown>
): Promise<MCPExplanationResponse> {
  let retries = 0;
  let explanation = '';
  let validated = false;

  while (retries < MAX_RETRIES && !validated) {
    retries++;

    // Generate explanation (mock LLM call)
    explanation = generateMockExplanation(transformationType, params);

    // Create diagnostic to validate
    const testDiagnostic: Partial<Diagnostic> = {
      id: `CHAOS_${transformationType.toUpperCase()}`,
      context: `chaos.transform.${transformationType}`,
      severity: 'info',
      params,
      explanation,
    };

    // Validate against Lingo
    const validationResult = validateDiagnostic(testDiagnostic);
    validated = validationResult.valid;

    if (!validated) {
      // In production, would regenerate with different prompt
      console.warn(`MCP explanation validation failed (attempt ${retries}):`, validationResult.errors);
    }
  }

  return {
    explanation,
    validated,
    retries,
  };
}

/**
 * Mock LLM call for explanation generation
 * In production, replace with actual OpenAI/Anthropic API call
 */
function generateMockExplanation(
  transformationType: string,
  params: Record<string, unknown>
): string {
  const generator = TRANSFORMATION_EXPLANATIONS[transformationType];
  
  if (generator) {
    return generator(params);
  }

  // Fallback generic explanation
  return `
    Transformation '${transformationType}' was applied to the intermediate representation. 
    This modification helps obscure the program's original structure while preserving 
    its runtime behavior. Parameters: ${JSON.stringify(params)}.
  `.trim().replace(/\s+/g, ' ');
}

/**
 * Build MCP prompt for LLM (for reference - would be used in production)
 */
export function buildMCPPrompt(
  transformationType: string,
  params: Record<string, unknown>
): string {
  return `
You are a compiler optimization expert. Explain the following transformation in clear, educational terms.

Transformation Type: ${transformationType}
Parameters: ${JSON.stringify(params, null, 2)}

Requirements:
1. Use ONLY these technical terms: ${glossary.slice(0, 20).join(', ')}
2. Keep explanation under 100 words
3. Focus on semantic preservation
4. Explain WHY the transformation is safe
5. Be suitable for computer science students

Provide a clear, concise explanation:
  `.trim();
}

/**
 * Generate explanations for all diagnostics
 */
export async function generateAllExplanations(
  diagnostics: Diagnostic[]
): Promise<Map<string, MCPExplanationResponse>> {
  const explanations = new Map<string, MCPExplanationResponse>();

  for (const diag of diagnostics) {
    if (!diag.explanation) {
      const transformationType = diag.id
        .replace(/^CHAOS_/, '')
        .toLowerCase()
        .replace(/_/g, '');

      const response = await generateExplanation(
        transformationType,
        diag.params ?? {}
      );

      explanations.set(diag.id, response);
    }
  }

  return explanations;
}

// ============================================================================
// STUDENT VS RESEARCHER MODE EXPLANATIONS
// ============================================================================

export type ExplanationMode = 'student' | 'researcher';

const STUDENT_TERMS: Record<string, string> = {
  'opaquePredicates': 'hidden conditions',
  'flattening': 'execution restructuring',
  'substitution': 'instruction replacement',
  'numberEncoding': 'number hiding',
  'ir': 'intermediate code',
  'xor': 'exclusive or',
  'semantic': 'behavioral',
};

const RESEARCHER_TERMS: Record<string, string> = {
  'hidden conditions': 'opaque predicates',
  'execution restructuring': 'control flow flattening',
  'instruction replacement': 'instruction substitution',
  'number hiding': 'number encoding',
  'intermediate code': 'IR (three-address code)',
  'exclusive or': 'XOR bitwise operation',
  'behavioral': 'semantic',
};

/**
 * Adapt explanation for target audience
 */
export function adaptExplanation(
  explanation: string,
  mode: ExplanationMode
): string {
  const terms = mode === 'student' ? STUDENT_TERMS : RESEARCHER_TERMS;
  let adapted = explanation;

  for (const [from, to] of Object.entries(terms)) {
    adapted = adapted.replace(new RegExp(from, 'gi'), to);
  }

  return adapted;
}

/**
 * Get simplified transformation name for students
 */
export function getDisplayName(
  transformationType: string,
  mode: ExplanationMode
): string {
  if (mode === 'student') {
    return STUDENT_TERMS[transformationType.toLowerCase()] ?? transformationType;
  }
  return transformationType;
}
